spring:
  ##################################################
  # _   _                          _             __
  #| |_| |__  _   _ _ __ ___   ___| | ___  __ _ / _|
  #| __| '_ \| | | | '_ ` _ \ / _ \ |/ _ \/ _` | |_
  #| |_| | | | |_| | | | | | |  __/ |  __/ (_| |  _|
  # \__|_| |_|\__, |_| |_| |_|\___|_|\___|\__,_|_|
  #           |___/
  ##################################################
  thymeleaf:
    cache: true